logging:
  level:
    ROOT: INFO
    nl.medicaldataworks.railway.central: DEBUG

server:
  port: 8080

keycloak:
  auth-server-url: http://localhost:9080/auth
  realm: railway
#  bearer-only: true
  resource: central
  allow-any-hostname: true
  autodetect-bearer-only: true
  credentials.secret: "e5339213-1346-48b3-b25c-cbe16dc42ca6"

spring:
  main:
   allow-bean-definition-overriding: true
  application:
    name: railway
  profiles:
    active: dev
    include:
      - swagger
  jmx:
    enabled: false
  data:
    jpa:
      repositories:
        bootstrap-mode: deferred
  datasource:
    url: jdbc:h2:mem:railway
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    database: H2
    properties:
      hibernate.id.new_generator_mappings: true
      hibernate.connection.provider_disables_autocommit: true
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false
  liquibase:
    contexts: dev
  messages:
    basename: i18n/messages
