logging:
  level:
    ROOT: INFO
    nl.medicaldataworks.railway: DEBUG

spring:
  profiles:
    active: dev
    include:
      - swagger
  jackson:
    serialization:
      indent-output: true
  datasource:
    url: jdbc:h2:file:./target/h2db/db/railway;DB_CLOSE_DELAY=-1
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    database: H2
    properties:
      hibernate.id.new_generator_mappings: true
      hibernate.connection.provider_disables_autocommit: true
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false
  liquibase:
    contexts: dev

server:
  port: 8080