logging:
  level:
    ROOT: INFO
    nl.medicaldataworks.railway: DEBUG

server:
  port: 8080

keycloak:
  auth-server-url: http://localhost:9080/auth
  realm: railway
  resource: central
  principal-attribute: preferred_username
  public-client: true

spring:
  main:
   allow-bean-definition-overriding: true
  application:
    name: railway
  profiles:
    active: dev
    include:
      - swagger
  jmx:
    enabled: false
  data:
    jpa:
      repositories:
        bootstrap-mode: deferred
  datasource:
    url: jdbc:h2:file:./target/h2db/db/railway;DB_CLOSE_DELAY=-1
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    database: H2
    properties:
      hibernate.id.new_generator_mappings: true
      hibernate.connection.provider_disables_autocommit: true
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false
  liquibase:
    contexts: dev
  messages:
    basename: i18n/messages
