logging:
  level:
    ROOT: INFO
    nl.medicaldataworks.railway.central: DEBUG

server:
  port: 8080

keycloak:
  auth-server-url: https://dcra-keycloak.railway.medicaldataworks.nl/auth
  realm: railway
  resource: central
  allow-any-hostname: true
  autodetect-bearer-only: true
  credentials.secret: "e5339213-1346-48b3-b25c-cbe16dc42ca6"
  enabled: true

spring:
  main:
   allow-bean-definition-overriding: true
  application:
    name: railway
  profiles:
    active: dev
    include:
      - swagger
  jmx:
    enabled: false
  datasource:
    url: jdbc:h2:file:./target/h2db/db/railway;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
    database: H2
    properties:
      hibernate.id.new_generator_mappings: true
      hibernate.connection.provider_disables_autocommit: true
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false
  messages:
    basename: i18n/messages
