logging:
  level:
    root: INFO
    nl.medicaldataworks: INFO
  #    org.springframework.web: DEBUG
  file:
    name: central.log

server:
  port: 8080
  forward-headers-strategy: native

keycloak:
  auth-server-url: https://dcra-keycloak.railway.medicaldataworks.nl/auth
  realm: railway
  resource: central
  allow-any-hostname: true
  autodetect-bearer-only: true
  credentials.secret: "c1df0827-4408-40a8-8181-1372a19f0a83"
  enabled: true
  confidential-port: 443
  ssl-required: none

spring:
  main:
   allow-bean-definition-overriding: true
  application:
    name: railway
  profiles:
    active: dev
    include:
      - swagger
  jmx:
    enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/railway
    username: railway
    password: AblexaVerEsT
  jpa:
    hibernate:
      ddl-auto: update
  messages:
    basename: i18n/messages
