version: '2'
services:
    keycloak:
        image: jboss/keycloak:7.0.0
        command:
          [
            '-b',
            '0.0.0.0',
            '-Dkeycloak.migration.action=import',
            '-Dkeycloak.migration.provider=dir',
            '-Dkeycloak.migration.dir=/opt/jboss/keycloak/realm-config',
            '-Dkeycloak.migration.strategy=OVERWRITE_EXISTING',
            '-Djboss.socket.binding.port-offset=1000',
          ]
        volumes:
          - ./realm-config:/opt/jboss/keycloak/realm-config
        environment:
          - KEYCLOAK_USER=admin
          - KEYCLOAK_PASSWORD=admin
          - DB_VENDOR=h2
        ports:
          - 9080:9080
          - 9443:9443
          - 10990:10990
    central:
        image: java:8-jre
        command:
          - java -jar /opt/central/target/central-0.0.1-SNAPSHOT.jar
        volumes:
          - ../../../target:/opt/central/target
        ports:
          - 8080:8080
