version: '2'
services:
  keycloak_db:
    image: postgres:10.4
    volumes:
      - ./keycloak-database/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=AblexaVerEsT
  keycloak:
    image: jboss/keycloak:7.0.0
    command:
      [
        '-b',
        '0.0.0.0',
        '-Djboss.socket.binding.port-offset=1000',
      ]
    volumes:
      - ./realm-config:/opt/jboss/keycloak/realm-config
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_VENDOR=POSTGRES
      - DB_ADDR=postgres
      - DB_DATABASE=keycloak
      - DB_USER=keycloak
      - DB_SCHEMA=public
      - DB_PASSWORD=AblexaVerEsT
    ports:
      - 9080:9080
      - 9443:9443
      - 10990:10990
    links:
      - keycloak_db:dbhost
    depends_on:
      - "keycloak_db"
