version: '2'
services:
  central:
    image: registry.gitlab.com/medicaldataworks/railway/central:latest
    volumes:
      - /opt/central/containers/application.yml:/app/application.yml
    ports:
      - 8080:8080
  railway_db:
    image: postgres:10.4
    volumes:
      - /opt/railway-database/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=railway
      - POSTGRES_USER=railway
      - POSTGRES_PASSWORD=AblexaVerEsT
  keycloak:
    image: jboss/keycloak:7.0.0
    command:
      [
        '-b',
        '0.0.0.0',
        '-Djboss.socket.binding.port-offset=1000',
      ]
    volumes:
      - ./realm-config:/opt/jboss/keycloak/realm-config
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_VENDOR=POSTGRES
      - DB_ADDR=railway_db
      - DB_DATABASE=railway
      - DB_USER=railway
      - DB_SCHEMA=public
      - DB_PASSWORD=AblexaVerEsT
    ports:
      - 9080:9080
      - 9443:9443
      - 10990:10990
    links:
      - railway_db:dbhost
    depends_on:
      - "railway_db"
