create table if not exists task (
    id bigint generated by default as identity,
    calculation_status integer not null,
    creation_timestamp timestamp,
    result varchar(255),
    master bit,
    input varchar(255),
    station_id bigint,
    train_id bigint,
    iteration bigint,
    primary key (id));
create table if not exists station (
    id bigint generated by default as identity,
    name varchar(255) not null,
    primary key (id));
create table if not exists train (
    id bigint generated by default as identity,
    calculation_status integer not null,
    docker_image_url varchar(255) not null,
    name varchar(255),
    owner_id varchar(255) not null,
    current_iteration bigint,
    primary key (id));